[package]
name = "majdool"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.28"
tokio = { version = "1", features = ["fs", "io-util", "macros", "rt-multi-thread"] }
tokio-postgres = "0.7"
